### ISSUE TITLE
Repo not created when node has large disk space

### ISSUE THREAD

**Issue by kounoike** [takezoe/distributed-git-server#1]
I tried with two node. Ubuntu 16.10 x64 and Raspberry pi 3.
But Ubuntu node doesn't create repo.

```shell-session
kounoike@myserver:~/distributed-git-server/dgit-controller-server$ cur -d "" http://localhost:8080/api/repos/dgit_test
kounoike@myserver:~/distributed-git-server/dgit-controller-server$ curl http://localhost:8080/api/nodes
[{"node":"http://localhost:8081","diskUsage":0.9790734247221924,"repos":[]},{"node":"http://raspberrypi.local:8081","diskUsage":0.5193819272268632,"repos":["dgit_test"]}]
kounoike@myserver:~/distributed-git-server/dgit-controller-server$ df /tmp
Filesystem      1K-blocks     Used  Available Use% Mounted on
/dev/sda2      2859026248 59829632 2653943344   3% /
```

This result says "Ubuntu node(localhost) has large diskUsage". Actually, myserver has large free space.

by this line, `diskUsage` calculated by `free / total`. It means "Free %". It maybe bug.

https://github.com/takezoe/distributed-git-server/blob/95fcce4e340dd089601bcd97d42253e80f08825f/dgit-repository-server/src/main/scala/com/github/takezoe/dgit/repository/InitializeListener.scala#L47

**Comment by takezoe** [comment]
@kounoike Oops... Thanks for reporting.
